package com.automation.exceptions;

public enum CustomExceptionType {
    UNDEFINED,
    VERIFICATION_FAILED,
    VALIDATION_FAILED,
    PROCESSING_FAILED,
    UNSATISFIED_IMPLICIT_ASSUMPTION,
    INCOMPLETE_PARAMS,
    IO_ERROR,
    ELEMENT_NOT_FOUND
}
